# Generated by Django 5.2.5 on 2025-08-25 19:51

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('depth', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('is_published', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'gallery_image',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
