# Generated by Django 5.2.6 on 2025-09-19 10:16

import artgallery.models.heroimage
import artgallery.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artgallery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(storage=artgallery.storage_backends.BunnyStorage(), upload_to=artgallery.models.heroimage.hero_image_upload_to)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
