# Generated by Django 5.2.6 on 2025-09-04 02:11

import artgallery.models.herovideo
import artgallery.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artgallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herovideo',
            name='video',
            field=models.FileField(storage=artgallery.storage_backends.BunnyStorage(), upload_to=artgallery.models.herovideo.hero_video_upload_to),
        ),
    ]
