# Generated by Django 5.2.4 on 2025-08-11 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artgallery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='videos/')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='video_posters/')),
                ('size_label', models.CharField(blank=True, max_length=32)),
                ('recorded_at', models.DateField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='HeroSection',
        ),
    ]
