# Generated by Django 5.2.5 on 2025-08-27 22:22

import cloudinary.models
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artgallery', '0002_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='duration_seconds',
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=cloudinary.models.CloudinaryField(max_length=255, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'webm', 'mkv', 'm4v', 'avi'])], verbose_name='video'),
        ),
    ]
