# Generated by Django 5.2.6 on 2025-09-04 02:12

import artgallery.models.artwork
import artgallery.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artgallery', '0002_alter_herovideo_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artworkimage',
            name='image',
            field=models.ImageField(storage=artgallery.storage_backends.BunnyStorage(), upload_to=artgallery.models.artwork.artwork_image_upload_to),
        ),
        migrations.AlterField(
            model_name='artworkvideo',
            name='video',
            field=models.FileField(storage=artgallery.storage_backends.BunnyStorage(), upload_to=artgallery.models.artwork.artwork_video_upload_to),
        ),
    ]
