# Generated by Django 5.2.4 on 2025-08-13 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artgallery', '0003_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
